USE MapfreQOA
GO


UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 67 WHERE N_ID_ZONAL = 452
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = NULL WHERE N_ID_ZONAL = 434

UPDATE T_TEMP_USUARIOMAPFRE SET NRO_DOC = NULL WHERE NRO_DOC = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE1 = NULL WHERE NOMBRE1 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE2 = NULL WHERE NOMBRE2 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO1 = NULL WHERE APELLIDO1 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO2 = NULL WHERE APELLIDO2 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET EMAIL = NULL WHERE EMAIL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET COD_VENDEDOR = NULL WHERE COD_VENDEDOR = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR = NULL WHERE VENDEDOR = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR_ESTADO = NULL WHERE VENDEDOR_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET COD_PTO_VENTA = NULL WHERE COD_PTO_VENTA = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA = NULL WHERE PUNTO_VENTA = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA_ESTADO = NULL WHERE PUNTO_VENTA_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = NULL WHERE COD_SUCURSAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL = NULL WHERE SUCURSAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL_ESTADO = NULL WHERE SUCURSAL_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL = NULL WHERE CANAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ESTADO = NULL WHERE CANAL_ESTADO = ' '

UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 6 WHERE CANAL_ID = 12  --CAJA PIURA
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 7 WHERE CANAL_ID = 11  --CAJA SULLANA
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 0 WHERE CANAL_ID IS NULL  --MAPFRE

UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 3 WHERE TIPO_DOC_ID = 122 --DNI
UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 736 WHERE TIPO_DOC_ID = 127 --OTRO DOC

UPDATE TMP
SET TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL
FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_ZONAL TMZ 
ON TMP.COD_SUCURSAL = TMZ.C_COD_ZONAL AND TMP.CANAL_ID_GLOBAL = 6 AND TMZ.N_ID_ENTIDAD = 6
WHERE TMZ.N_ID_TIPOZONAL = 406 
  AND TMZ.C_COD_ZONAL IS NOT NULL 
  AND TMP.COD_SUCURSAL IS NOT NULL

UPDATE TMP
SET TMP.COD_ROL_GLOBAL = PER.N_ID_PERFIL
FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_PERFIL PER
ON TMP.COD_ROL = CAST(PER.C_COD_REFERENCIA AS INT) AND PER.C_COD_REFERENCIA IS NOT NULL
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 

UPDATE TMP
SET TMP.USUARIO_OBS = 'Duplicado'
FROM T_TEMP_USUARIOMAPFRE TMP
WHERE COD_ROL_GLOBAL IS NOT NULL 
  AND EXISTS(
	SELECT DISTINCT T.USUARIO
	FROM T_TEMP_USUARIOMAPFRE T
	WHERE T.COD_ROL_GLOBAL IS NOT NULL 
	  AND T.USUARIO = TMP.USUARIO
	GROUP BY T.USUARIO
	HAVING COUNT(T.USUARIO) > 1
  )

GO