USE MapfreQOA
GO

INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Vendedor','VE',1,8,'admin',GETDATE(),8,'10')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Vendedor Piura','VEPIURA',1,8,'admin',GETDATE(),8,'12')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Jefe de Agencia','JEFAG',1,8,'admin',GETDATE(),9,'20')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Gestor Comercial','GESCOM',1,8,'admin',GETDATE(),9,'22')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Consultor','CONSULTA',1,8,'admin',GETDATE(),9,'23')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Jefe de Productos Generales','JEFPROD',1,8,'admin',GETDATE(),9,'25')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Supervisor Caja Piura','SUPPIURA',1,8,'admin',GETDATE(),9,'33')
INSERT INTO [dbo].[T_MAE_PERFIL]
           ([C_DES_PERFIL],[C_ABR_PERFIL],[N_IND_ACTIVO],[N_ID_ESTADO],[C_COD_USUCREACION],[D_FEC_CREACION],[N_ID_MCA_VENDEDOR],[C_COD_REFERENCIA])
     VALUES('Soporte','SOPORTE',1,8,'admin',GETDATE(),9,'36')



UPDATE T_MAE_ZONAL SET C_COD_ZONAL = NULL WHERE N_ID_ZONAL = 434
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 67 WHERE N_ID_ZONAL = 452
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 999 WHERE N_ID_ZONAL = 440
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 998 WHERE N_ID_ZONAL = 443
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 997 WHERE N_ID_ZONAL = 450
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 996 WHERE N_ID_ZONAL = 441
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 995 WHERE N_ID_ZONAL = 442
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 994 WHERE N_ID_ZONAL = 435
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 993 WHERE N_ID_ZONAL = 438
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 992 WHERE N_ID_ZONAL = 447
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 991 WHERE N_ID_ZONAL = 448
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 990 WHERE N_ID_ZONAL = 436
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 989 WHERE N_ID_ZONAL = 439
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 988 WHERE N_ID_ZONAL = 437
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 985 WHERE N_ID_ZONAL = 451
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 984 WHERE N_ID_ZONAL = 449
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 983 WHERE N_ID_ZONAL = 446
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 982 WHERE N_ID_ZONAL = 444
UPDATE T_MAE_ZONAL SET C_COD_ZONAL = 981 WHERE N_ID_ZONAL = 445
UPDATE T_MAE_ZONAL SET N_ID_ZONALPADRE = 229 WHERE N_ID_ENTIDAD = 6 and N_ID_TIPOZONAL = 406 and N_ID_ZONALPADRE = 227

UPDATE T_TEMP_USUARIOMAPFRE SET NRO_DOC = NULL WHERE NRO_DOC = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE1 = NULL WHERE NOMBRE1 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE2 = NULL WHERE NOMBRE2 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO1 = NULL WHERE APELLIDO1 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO2 = NULL WHERE APELLIDO2 = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET EMAIL = NULL WHERE EMAIL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET COD_VENDEDOR = NULL WHERE COD_VENDEDOR = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR = NULL WHERE VENDEDOR = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR_ESTADO = NULL WHERE VENDEDOR_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET COD_PTO_VENTA = NULL WHERE COD_PTO_VENTA = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA = NULL WHERE PUNTO_VENTA = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA_ESTADO = NULL WHERE PUNTO_VENTA_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = NULL WHERE COD_SUCURSAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL = NULL WHERE SUCURSAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL_ESTADO = NULL WHERE SUCURSAL_ESTADO = ' '
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL = NULL WHERE CANAL = 'NULL'
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ESTADO = NULL WHERE CANAL_ESTADO = ' '

UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 6 WHERE CANAL_ID = 12  --CAJA PIURA
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 7 WHERE CANAL_ID = 11  --CAJA SULLANA
UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 0 WHERE CANAL_ID IS NULL  --MAPFRE

UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 3 WHERE TIPO_DOC_ID = 122 --DNI
UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 736 WHERE TIPO_DOC_ID = 127 --OTRO DOC

UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 999 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 258 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 998 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 268 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 997 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 278 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 996 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 260 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 995 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 267 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 994 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 253 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 993 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 256 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 992 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 274 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 991 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 275 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 990 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 254 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 989 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 257 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 988 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 255 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 986 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 296 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 985 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 279 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 984 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 277 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 983 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 273 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 982 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 271 
UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 981 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 272 


UPDATE TMP
SET TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL
FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_ZONAL TMZ 
ON TMP.COD_SUCURSAL = TMZ.C_COD_ZONAL AND TMP.CANAL_ID_GLOBAL = 6 AND TMZ.N_ID_ENTIDAD = 6
WHERE TMZ.N_ID_TIPOZONAL = 406 
  AND TMZ.C_COD_ZONAL IS NOT NULL 
  AND TMP.COD_SUCURSAL IS NOT NULL

UPDATE TMP
SET TMP.COD_ROL_GLOBAL = PER.N_ID_PERFIL
FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_PERFIL PER
ON TMP.COD_ROL = CAST(PER.C_COD_REFERENCIA AS INT) AND PER.C_COD_REFERENCIA IS NOT NULL
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 

UPDATE TMP
SET TMP.USUARIO_OBS = 'Duplicado'
FROM T_TEMP_USUARIOMAPFRE TMP
WHERE COD_ROL_GLOBAL IS NOT NULL 
  AND EXISTS(
	SELECT DISTINCT T.USUARIO
	FROM T_TEMP_USUARIOMAPFRE T
	WHERE T.COD_ROL_GLOBAL IS NOT NULL 
	  AND T.USUARIO = TMP.USUARIO
	GROUP BY T.USUARIO
	HAVING COUNT(T.USUARIO) > 1
  )



INSERT INTO [dbo].[T_MAE_PERSONA] (
	[N_ID_ENTIDAD],
	[N_ID_TIPOPERSONA],
	[N_ID_TIPOIDENTIDAD],
	[C_VAL_DOCIDENTIDAD],
	[C_APE_PATERNO],
	[C_APE_MATERNO],
	[C_NOM_PERSONA],
	[C_NOM_COMPLETO],
	[N_ID_UBIGEO],
	[C_DIR_CORREO],
	[C_VAL_CODREFERENCIA],
	[N_IND_ACTIVO],
	[N_ID_ESTADO],
	[C_COD_USUCREACION],
	[D_FEC_CREACION] )
SELECT 
	CANAL_ID_GLOBAL,
	0,
	TIPO_DOC_ID_GLOBAL,
	ISNULL(NRO_DOC, ''),
	ISNULL(APELLIDO1, ''),
	ISNULL(APELLIDO2, ''),
	RTRIM(ISNULL(NOMBRE1, '') + ' ' + ISNULL(NOMBRE2, '')),
	IIF(ISNULL(VENDEDOR_ID, '') = '', RTRIM(ISNULL(NOMBRE1, '') + ' ' + ISNULL(NOMBRE2, '') + ' ' + ISNULL(APELLIDO1, '') + ' ' + ISNULL(APELLIDO2, '')), ISNULL(VENDEDOR, '')),
	0,
	ISNULL(EMAIL, ''),
	USUARIO_ID,
	1,
	8,
	'admin',
	GETDATE()
FROM T_TEMP_USUARIOMAPFRE
WHERE CANAL_ID_GLOBAL IN (6, 0)
  AND COD_ROL_GLOBAL IS NOT NULL 
  AND USUARIO_OBS IS NULL



INSERT INTO [dbo].[T_DET_PERSONA] (
	[N_ID_PERSONA],
	[N_ID_ESTABLECIMIENTO],
	[N_ID_TIPOCANALVENTA],
	[N_ID_TIPOROL],
	[N_IND_ACTIVO],
	[N_ID_ESTADO],
	[C_COD_USUCREACION],
	[D_FEC_CREACION],
	[N_ID_TITULARCUENTA],
	[N_ID_TERCEROPAGO] )
SELECT
	PER.N_ID_PERSONA,
	TMZ.N_ID_ESTABLECIMIENTO,
	CASE WHEN COD_ROL_GLOBAL IN (23, 36) THEN 570 ELSE 569 END,
	CASE WHEN COD_ROL_GLOBAL IN (10, 12) THEN 312 WHEN COD_ROL_GLOBAL = 23 THEN 571 ELSE 311 END,
	1,
	8,
	'admin',
	GETDATE(),
	0,
	0
FROM T_TEMP_USUARIOMAPFRE TMP 
INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
LEFT JOIN T_MAE_ZONAL TMZ ON TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL AND TMZ.N_ID_ENTIDAD = 6 AND TMZ.N_ID_TIPOZONAL = 406
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
  AND TMP.USUARIO_OBS IS NULL
  
  

INSERT INTO [dbo].[T_MAE_USUARIO]
           ([N_ID_PERSONA]
           ,[C_COD_USUARIO]
           ,[C_VAL_CLAVE]
           ,[N_ID_TIPOUSUARIO]
           ,[N_NUM_INTENTO]
           ,[D_FEC_ACTIVACION]
           ,[D_FEC_EXPIRACION]
           ,[D_FEC_CLAVE]
           ,[D_FEC_BLOQUEO]
           ,[N_IND_ACTIVADO]
           ,[N_IND_ACTIVO]
           ,[N_ID_ESTADO]
           ,[C_COD_USUCREACION]
           ,[D_FEC_CREACION]
           ,[D_FEC_CUENTA]
           ,[C_MCA_EXTERNO])
SELECT PER.N_ID_PERSONA,
	   TMP.USUARIO,
	   'l22GZw7z+Y4GkCNLyN+fCQ==',
	   0,
	   0,
	   GETDATE(),
	   GETDATE() + 30,
	   GETDATE(),
	   GETDATE() + 365,
	   1,
	   1,
	   8,
	   'admin',
	   GETDATE(),
	   GETDATE() + 365,
	   'N'
FROM T_TEMP_USUARIOMAPFRE TMP
INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
  AND TMP.USUARIO_OBS IS NULL
	  

INSERT INTO [dbo].[T_DET_USUARIOPERFIL]
           ([N_ID_USUARIO]
           ,[N_ID_PERFIL]
           ,[N_IND_ACTIVO]
           ,[N_ID_ESTADO]
           ,[C_COD_USUCREACION]
           ,[D_FEC_CREACION])
SELECT	TMU.N_ID_USUARIO,
		TMP.COD_ROL_GLOBAL,
		1,
		8,
		'admin',
		GETDATE()
FROM T_TEMP_USUARIOMAPFRE TMP 
INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
INNER JOIN T_MAE_USUARIO TMU ON TMP.USUARIO = TMU.C_COD_USUARIO AND PER.N_ID_PERSONA = TMU.N_ID_PERSONA
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
  AND TMP.USUARIO_OBS IS NULL



GO