USE MapfreQOA
GO


INSERT INTO [dbo].[T_MAE_PERSONA] (
	[N_ID_ENTIDAD],
	[N_ID_TIPOPERSONA],
	[N_ID_TIPOIDENTIDAD],
	[C_VAL_DOCIDENTIDAD],
	[C_APE_PATERNO],
	[C_APE_MATERNO],
	[C_NOM_PERSONA],
	[C_NOM_COMPLETO],
	[N_ID_UBIGEO],
	[C_DIR_CORREO],
	[C_VAL_CODREFERENCIA],
	[N_IND_ACTIVO],
	[N_ID_ESTADO],
	[C_COD_USUCREACION],
	[D_FEC_CREACION] )
SELECT 
	CANAL_ID_GLOBAL,
	0,
	TIPO_DOC_ID_GLOBAL,
	ISNULL(NRO_DOC, ''),
	ISNULL(APELLIDO1, ''),
	ISNULL(APELLIDO2, ''),
	RTRIM(ISNULL(NOMBRE1, '') + ' ' + ISNULL(NOMBRE2, '')),
	IIF(ISNULL(VENDEDOR_ID, '') = '', RTRIM(ISNULL(NOMBRE1, '') + ' ' + ISNULL(NOMBRE2, '') + ' ' + ISNULL(APELLIDO1, '') + ' ' + ISNULL(APELLIDO2, '')), ISNULL(VENDEDOR, '')),
	0,
	ISNULL(EMAIL, ''),
	USUARIO_ID,
	1,
	8,
	'admin',
	GETDATE()
FROM T_TEMP_USUARIOMAPFRE
WHERE CANAL_ID_GLOBAL IN (6, 0)
  AND COD_ROL_GLOBAL IS NOT NULL 
  AND USUARIO_OBS IS NULL



INSERT INTO [dbo].[T_DET_PERSONA] (
	[N_ID_PERSONA],
	[N_ID_ESTABLECIMIENTO],
	[N_ID_TIPOCANALVENTA],
	[N_ID_TIPOROL],
	[N_IND_ACTIVO],
	[N_ID_ESTADO],
	[C_COD_USUCREACION],
	[D_FEC_CREACION],
	[N_ID_TITULARCUENTA],
	[N_ID_TERCEROPAGO] )
SELECT
	PER.N_ID_PERSONA,
	TMZ.N_ID_ESTABLECIMIENTO,
	CASE WHEN COD_ROL_GLOBAL IN (23, 36) THEN 570 ELSE 569 END,
	CASE WHEN COD_ROL_GLOBAL IN (10, 12) THEN 312 WHEN COD_ROL_GLOBAL = 23 THEN 571 ELSE 311 END,
	1,
	8,
	'admin',
	GETDATE(),
	0,
	0
FROM T_TEMP_USUARIOMAPFRE TMP 
INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
LEFT JOIN T_MAE_ZONAL TMZ ON TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL AND TMZ.N_ID_ENTIDAD = 6 AND TMZ.N_ID_TIPOZONAL = 406
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
  AND TMP.USUARIO_OBS IS NULL
  
  

INSERT INTO [dbo].[T_MAE_USUARIO]
           ([N_ID_PERSONA]
           ,[C_COD_USUARIO]
           ,[C_VAL_CLAVE]
           ,[N_ID_TIPOUSUARIO]
           ,[N_NUM_INTENTO]
           ,[D_FEC_ACTIVACION]
           ,[D_FEC_EXPIRACION]
           ,[D_FEC_CLAVE]
           ,[D_FEC_BLOQUEO]
           ,[N_IND_ACTIVADO]
           ,[N_IND_ACTIVO]
           ,[N_ID_ESTADO]
           ,[C_COD_USUCREACION]
           ,[D_FEC_CREACION]
           ,[D_FEC_CUENTA]
           ,[C_MCA_EXTERNO])
SELECT PER.N_ID_PERSONA,
	   TMP.USUARIO,
	   'l22GZw7z+Y4GkCNLyN+fCQ==',
	   0,
	   0,
	   GETDATE(),
	   GETDATE() + 30,
	   GETDATE(),
	   GETDATE() + 365,
	   1,
	   1,
	   8,
	   'admin',
	   GETDATE(),
	   GETDATE() + 365,
	   'N'
FROM T_TEMP_USUARIOMAPFRE TMP
INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
  AND TMP.USUARIO_OBS IS NULL
	  
	  
GO