USE MapfreQOA
GO


INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 20, 1, 8, 'admin', GETDATE())

INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (88, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (89, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (90, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (91, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (92, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (94, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (95, 21, 1, 8, 'admin', GETDATE())

INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (88, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (89, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (90, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (91, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (92, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (94, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (95, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (76, 22, 1, 8, 'admin', GETDATE())


INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (89, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (90, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (92, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (95, 23, 1, 8, 'admin', GETDATE())

INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 24, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (88, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (91, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (94, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (76, 25, 1, 8, 'admin', GETDATE())

INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 26, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (88, 26, 1, 8, 'admin', GETDATE())


INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (17, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (88, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (89, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (90, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (91, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (92, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (94, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (95, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (76, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (69, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (74, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (75, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (93, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (21, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (23, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (44, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (45, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (46, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (48, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (20, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (29, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (60, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (83, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (84, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (85, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (86, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (25, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_DET_OPCIONPERFIL (N_ID_OPCION, N_ID_PERFIL, N_IND_ACTIVO, N_ID_ESTADO, C_COD_USUCREACION, D_FEC_CREACION) 
	VALUES (26, 27, 1, 8, 'admin', GETDATE())
	




INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 32, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 33, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 32, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 33, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 32, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 33, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 32, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 33, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 32, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 33, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 34, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 20, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 21, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 24, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 29, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 22, 31, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 23, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 24, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 24, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 26, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 29, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 25, 31, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 26, 24, 1, 8, 'admin', GETDATE())

INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 1, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 22, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 5, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 23, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 2, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 25, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 4, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 27, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 6, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 24, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 21, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 26, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 29, 1, 8, 'admin', GETDATE())
INSERT INTO T_MAE_PERFIL_PERMISO_OPCION (N_ID_PERMISO_OPCION,N_ID_PERFIL,N_ID_PERMISO,N_ID_ACTIVO,N_ID_ESTADO,C_COD_USUCREACION,D_FEC_CREACION) 
	VALUES (NULL, 27, 31, 1, 8, 'admin', GETDATE())




insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 27 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 24 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
	
insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 22 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
	
insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
	
insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 25 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
	
insert into T_MAE_USUARIO_CANAL_PTOVENTA
select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 26 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CANAL_PTOVENTA TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)




insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 27 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 24 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 22 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
	
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 26 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)


insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 14, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 14)

insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 15, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 15)

insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 16, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 16)
	  
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 17, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 17)
	  
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 18, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 23 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 18)
	  
	  
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 19, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 25 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 19)
	  
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 20, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 25 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 20)
	  
insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 27, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 25 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 27)

insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select TUP.N_ID_USUARIO, 5, 28, 0, 8, 1, GETDATE(), NULL, NULL
from T_DET_USUARIOPERFIL TUP
where TUP.N_ID_PERFIL = 25 and not exists (
	select TB.N_ID_USUARIO
	from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
	where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
	  and TB.N_ID_PRODUCTO = 28)



UPDATE T_TEMP_USUARIOMAPFRE
SET USUARIO_OBS = 'Migrado'
WHERE CANAL_ID_GLOBAL IN (6, 0)
  AND COD_ROL_GLOBAL IS NOT NULL 
  AND USUARIO_OBS IS NULL
  
	
GO