USE Nucleo



DECLARE @temp_persona AS TABLE (
	USUARIO_ID INT,
	CANAL_ID_GLOBAL INT,
	TIPO_DOC_ID_GLOBAL INT,
	NRO_DOC VARCHAR(15),
	NOMBRE1 VARCHAR(100),
	NOMBRE2 VARCHAR(100),
	APELLIDO1 VARCHAR(100),
	APELLIDO2 VARCHAR(100),
	VENDEDOR_ID INT,
	VENDEDOR VARCHAR(100),
	NOMBRE_COMPLETO VARCHAR(300),
	EMAIL VARCHAR(100)
)



insert into T_TEMP_USUARIOMAPFRE
		(USUARIO_ID
		,USUARIO
		,USUARIO_ESTADO
		,ACCOUNT
		,ACCOUNT_ESTADO
		,ACCOUNT_DESC
		,COD_USER
		,COD_ROL
		,ROL
		,ROL_DESC
		,PERSONA_ID
		,TIPO_DOC_ID
		,NRO_DOC
		,NOMBRE1
		,NOMBRE2
		,APELLIDO1
		,APELLIDO2
		,EMAIL
		,VENDEDOR_ID
		,COD_VENDEDOR
		,VENDEDOR
		,VENDEDOR_ESTADO
		,PUNTO_VENTA_ID
		,COD_PTO_VENTA
		,PUNTO_VENTA
		,PUNTO_VENTA_ESTADO
		,SUCURSAL_ID
		,COD_SUCURSAL
		,SUCURSAL
		,SUCURSAL_ESTADO
		,CANAL_ID
		,CANAL
		,CANAL_ESTADO)
select  TBU.USUARIO_ID,
		TBU.NOMBRE,
		TBU.ESTADO,
		SAC.TXT_ACC,
		SAC.STATUS,
		SAC.DESCRIPTION,
		SAC.COD_USER,
		SAR.COD_ROL,
		SRO.TXT_ROL,
		SRO.DESCRIPTION,
		TBU.PERSONA_ID,
		TBP.TIPO_DOC_ID,
		TBP.NRO_DOC,
		TBP.NOMBRE1,
		TBP.NOMBRE2,
		TBP.APELLIDO1,
		TBP.APELLIDO2,
		TBP.EMAIL,
		TBU.VENDEDOR_ID,
		TBV.COD_VENDEDOR,
		TBV.NOMBRE,
		TBV.ESTADO,
		TBV.PUNTO_VENTA_ID,
		TPV.COD_PTO_VENTA,
		TPV.NOMBRE,
		TPV.ESTADO,
		TPV.SUCURSAL_ID,
		TBS.COD_SUCURSAL,
		TBS.NOMBRE,
		TBS.ESTADO,
		TBS.CANAL_ID,
		TBC.NOMBRE,
		TBC.ESTADO
from	SGSM.dbo.TB_CDA_USUARIO TBU inner join 
		SGSM.dbo.SYS_ACCOUNT SAC on TBU.USUARIO_ID = SAC.COD_USER inner join 
		SGSM.dbo.SYS_ACCOUNT_ROL SAR on SAC.COD_ACC = SAR.COD_ACC inner join
		SGSM.dbo.SYS_ROL SRO on SAR.COD_ROL = SRO.COD_ROL left join
		SGSM.dbo.TB_ADM_PERSONA TBP on TBU.PERSONA_ID = TBP.PERSONA_ID left join 
		SGSM.dbo.TB_ADM_VENDEDOR TBV on TBU.VENDEDOR_ID = TBV.VENDEDOR_ID left join 
		SGSM.dbo.TB_ADM_PUNTO_VENTA TPV on TBV.PUNTO_VENTA_ID = TPV.PUNTO_VENTA_ID left join 
		SGSM.dbo.TB_ADM_SUCURSAL TBS on TPV.SUCURSAL_ID = TBS.SUCURSAL_ID left join 
		SGSM.dbo.TB_ADM_CANAL TBC on TBS.CANAL_ID = TBC.CANAL_ID
where	NOT EXISTS (
	SELECT TEMP.USUARIO
	FROM T_TEMP_USUARIOMAPFRE TEMP
	WHERE TEMP.USUARIO COLLATE Modern_Spanish_CI_AS = TBU.NOMBRE COLLATE Modern_Spanish_CI_AS
)

BEGIN TRY
	BEGIN TRANSACTION

		PRINT 'Updates - estandarizacion de datos'
		
		UPDATE T_TEMP_USUARIOMAPFRE SET NRO_DOC = NULL WHERE USUARIO_OBS IS NULL AND (NRO_DOC = 'NULL' OR RTRIM(LTRIM(NRO_DOC)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE1 = NULL WHERE USUARIO_OBS IS NULL AND (NOMBRE1 = 'NULL' OR RTRIM(LTRIM(NOMBRE1)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET NOMBRE2 = NULL WHERE USUARIO_OBS IS NULL AND (NOMBRE2 = 'NULL' OR RTRIM(LTRIM(NOMBRE2)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO1 = NULL WHERE USUARIO_OBS IS NULL AND (APELLIDO1 = 'NULL' OR RTRIM(LTRIM(APELLIDO1)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET APELLIDO2 = NULL WHERE USUARIO_OBS IS NULL AND (APELLIDO2 = 'NULL' OR RTRIM(LTRIM(APELLIDO2)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET EMAIL = NULL WHERE USUARIO_OBS IS NULL AND (EMAIL = 'NULL' OR RTRIM(LTRIM(EMAIL)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_VENDEDOR = NULL WHERE USUARIO_OBS IS NULL AND (COD_VENDEDOR = 'NULL' OR RTRIM(LTRIM(COD_VENDEDOR)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR = NULL WHERE USUARIO_OBS IS NULL AND (VENDEDOR = 'NULL' OR RTRIM(LTRIM(VENDEDOR)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET VENDEDOR_ESTADO = NULL WHERE USUARIO_OBS IS NULL AND VENDEDOR_ESTADO = ' '
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_PTO_VENTA = NULL WHERE USUARIO_OBS IS NULL AND (COD_PTO_VENTA = 'NULL' OR RTRIM(LTRIM(COD_PTO_VENTA)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA = NULL WHERE USUARIO_OBS IS NULL AND (PUNTO_VENTA = 'NULL' OR RTRIM(LTRIM(PUNTO_VENTA)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET PUNTO_VENTA_ESTADO = NULL WHERE USUARIO_OBS IS NULL AND PUNTO_VENTA_ESTADO = ' '
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = NULL WHERE USUARIO_OBS IS NULL AND (COD_SUCURSAL = 'NULL' OR RTRIM(LTRIM(COD_SUCURSAL)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL = NULL WHERE USUARIO_OBS IS NULL AND (SUCURSAL = 'NULL' OR RTRIM(LTRIM(SUCURSAL)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET SUCURSAL_ESTADO = NULL WHERE USUARIO_OBS IS NULL AND SUCURSAL_ESTADO = ' '
		UPDATE T_TEMP_USUARIOMAPFRE SET CANAL = NULL WHERE USUARIO_OBS IS NULL AND (CANAL = 'NULL' OR RTRIM(LTRIM(CANAL)) = '')
		UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ESTADO = NULL WHERE USUARIO_OBS IS NULL AND CANAL_ESTADO = ' '
		
		PRINT 'Updates - estandarizacion de nombre completo'
		
		UPDATE TMP
		SET TMP.NOMBRE_COMPLETO = IIF(ISNULL(TMP.VENDEDOR_ID, 0) = 0, UPPER(RTRIM(LTRIM(ISNULL(TMP.APELLIDO1, '') + ' ' + ISNULL(TMP.APELLIDO2, '') + ' ' + ISNULL(TMP.NOMBRE1, '') + ' ' + ISNULL(TMP.NOMBRE2, '')))), UPPER(RTRIM(LTRIM(ISNULL(TMP.VENDEDOR, '')))))
		FROM T_TEMP_USUARIOMAPFRE TMP

		UPDATE TMP 
		SET TMP.NOMBRE_COMPLETO = SUBSTRING(TMP.NOMBRE_COMPLETO, 2, 299) 
		FROM T_TEMP_USUARIOMAPFRE TMP
		WHERE NOMBRE_COMPLETO LIKE ' %'

		PRINT 'Updates - homologacion de identificadores'
		
		UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 6 WHERE CANAL_ID = 12  --CAJA PIURA
		UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 7 WHERE CANAL_ID = 11  --CAJA SULLANA
		UPDATE T_TEMP_USUARIOMAPFRE SET CANAL_ID_GLOBAL = 0 WHERE CANAL_ID IS NULL  --MAPFRE

		UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 3 WHERE TIPO_DOC_ID = 122 --DNI
		UPDATE T_TEMP_USUARIOMAPFRE SET TIPO_DOC_ID_GLOBAL = 736 WHERE TIPO_DOC_ID = 127 --OTRO DOC
		
		PRINT 'Updates - codigos de sucursal caja piura'

		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 999 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 258 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 998 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 268 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 997 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 278 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 996 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 260 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 995 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 267 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 994 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 253 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 993 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 256 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 992 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 274 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 991 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 275 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 990 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 254 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 989 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 257 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 988 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 255 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 986 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 296 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 985 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 279 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 984 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 277 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 983 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 273 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 982 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 271 
		UPDATE T_TEMP_USUARIOMAPFRE SET COD_SUCURSAL = 981 WHERE CANAL_ID_GLOBAL= 6 AND SUCURSAL_ID_GLOBAL IS NULL AND SUCURSAL_ID = 272
		
		PRINT 'Updates - homologacion de sucursal'

		UPDATE TMP
		SET TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL
		FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_ZONAL TMZ 
		ON TMP.COD_SUCURSAL = TMZ.C_COD_ZONAL AND TMP.CANAL_ID_GLOBAL = 6 AND TMZ.N_ID_ENTIDAD = 6
		WHERE TMZ.N_ID_TIPOZONAL = 406 
		  AND TMZ.C_COD_ZONAL IS NOT NULL 
		  AND TMP.COD_SUCURSAL IS NOT NULL
		  AND TMP.USUARIO_OBS IS NULL
		  AND TMP.SUCURSAL_ID_GLOBAL IS NULL

		PRINT 'Updates - homologacion de perfil'
		
		UPDATE TMP
		SET TMP.COD_ROL_GLOBAL = PER.N_ID_PERFIL
		FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_PERFIL PER
		ON TMP.COD_ROL = CAST(PER.C_COD_REFERENCIA AS INT) AND PER.C_COD_REFERENCIA IS NOT NULL
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 
		  AND TMP.USUARIO_OBS IS NULL
		  AND TMP.COD_ROL_GLOBAL IS NULL

		PRINT 'Updates - excluir duplicados'
		
		UPDATE TMP
		SET TMP.USUARIO_OBS = 'Duplicado',
			TMP.USUARIO_OBS_DATE = FORMAT(GETDATE(), 'yyyyMMdd')
		FROM T_TEMP_USUARIOMAPFRE TMP
		WHERE COD_ROL_GLOBAL IS NOT NULL 
		  AND EXISTS(
			SELECT DISTINCT T.USUARIO
			FROM T_TEMP_USUARIOMAPFRE T
			WHERE T.COD_ROL_GLOBAL IS NOT NULL 
			  AND T.USUARIO = TMP.USUARIO
			GROUP BY T.USUARIO
			HAVING COUNT(T.USUARIO) > 1
		  )
		
		PRINT 'Cargar datos de personas'
		;

		WITH TB_PERSONA AS (
			SELECT  USUARIO_ID, 
					NOMBRE_COMPLETO, 
					ROW_NUMBER() OVER (PARTITION BY NOMBRE_COMPLETO ORDER BY USUARIO_ID DESC) AS NUMFILA
			FROM T_TEMP_USUARIOMAPFRE TMP
			WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 
			  AND TMP.USUARIO_OBS IS NULL
			  AND TMP.COD_ROL_GLOBAL IS NOT NULL
			  
		)
		
		INSERT INTO @temp_persona
		SELECT  TMP.USUARIO_ID,
				TMP.CANAL_ID_GLOBAL,
				TMP.TIPO_DOC_ID_GLOBAL,
				TMP.NRO_DOC,
				TMP.NOMBRE1,
				TMP.NOMBRE2,
				TMP.APELLIDO1,
				TMP.APELLIDO2,
				TMP.VENDEDOR_ID,
				TMP.VENDEDOR,
				TMP.NOMBRE_COMPLETO,
				TMP.EMAIL
		FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN TB_PERSONA TB ON TMP.USUARIO_ID = TB.USUARIO_ID AND TMP.NOMBRE_COMPLETO = TB.NOMBRE_COMPLETO AND TB.NUMFILA = 1
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 
		  AND TMP.USUARIO_OBS IS NULL


		INSERT INTO [dbo].[T_MAE_PERSONA] (
			[N_ID_ENTIDAD],
			[N_ID_TIPOPERSONA],
			[N_ID_TIPOIDENTIDAD],
			[C_VAL_DOCIDENTIDAD],
			[C_APE_PATERNO],
			[C_APE_MATERNO],
			[C_NOM_PERSONA],
			[C_NOM_COMPLETO],
			[N_ID_UBIGEO],
			[C_DIR_CORREO],
			[C_VAL_CODREFERENCIA],
			[N_IND_ACTIVO],
			[N_ID_ESTADO],
			[C_COD_USUCREACION],
			[D_FEC_CREACION] )
		SELECT 
			TB.CANAL_ID_GLOBAL,
			0,
			TB.TIPO_DOC_ID_GLOBAL,
			ISNULL(TB.NRO_DOC, ''),
			ISNULL(TB.APELLIDO1, ''),
			ISNULL(TB.APELLIDO2, ''),
			RTRIM(ISNULL(TB.NOMBRE1, '') + ' ' + ISNULL(TB.NOMBRE2, '')),
			ISNULL(TB.NOMBRE_COMPLETO, ''),
			0,
			ISNULL(TB.EMAIL, ''),
			TB.USUARIO_ID,
			1,
			8,
			'admin',
			GETDATE()
		FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN @temp_persona TB ON TMP.USUARIO_ID = TB.USUARIO_ID AND TMP.NOMBRE_COMPLETO = TB.NOMBRE_COMPLETO
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
		  AND TMP.USUARIO_OBS IS NULL
		  AND TMP.COD_ROL_GLOBAL IS NOT NULL 


		INSERT INTO [dbo].[T_DET_PERSONA] (
			[N_ID_PERSONA],
			[N_ID_ESTABLECIMIENTO],
			[N_ID_TIPOCANALVENTA],
			[N_ID_TIPOROL],
			[N_IND_ACTIVO],
			[N_ID_ESTADO],
			[C_COD_USUCREACION],
			[D_FEC_CREACION],
			[N_ID_TITULARCUENTA],
			[N_ID_TERCEROPAGO] )
		SELECT
			PER.N_ID_PERSONA,
			TMZ.N_ID_ESTABLECIMIENTO,
			CASE WHEN COD_ROL_GLOBAL IN (23, 36) THEN 570 ELSE 569 END,
			CASE WHEN COD_ROL_GLOBAL IN (10, 12) THEN 312 WHEN COD_ROL_GLOBAL = 23 THEN 571 ELSE 311 END,
			1,
			8,
			'admin',
			GETDATE(),
			0,
			0
		FROM T_TEMP_USUARIOMAPFRE TMP 
		INNER JOIN T_MAE_PERSONA PER ON RTRIM(LTRIM(STR(TMP.USUARIO_ID))) = PER.C_VAL_CODREFERENCIA
		LEFT JOIN T_MAE_ZONAL TMZ ON TMP.SUCURSAL_ID_GLOBAL = TMZ.N_ID_ZONAL AND TMZ.N_ID_ENTIDAD = 6 AND TMZ.N_ID_TIPOZONAL = 406
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
		  AND TMP.USUARIO_OBS IS NULL
		  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
		  

		PRINT 'Cargar datos de usuarios'
		
		UPDATE TMP
		SET TMP.PERSONA_ID_GLOBAL = PER.N_ID_PERSONA
		FROM T_TEMP_USUARIOMAPFRE TMP INNER JOIN T_MAE_PERSONA PER ON TMP.NOMBRE_COMPLETO = PER.C_NOM_COMPLETO
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0) 
		  AND TMP.USUARIO_OBS IS NULL
		  AND TMP.COD_ROL_GLOBAL IS NOT NULL
		
		INSERT INTO [dbo].[T_MAE_USUARIO]
				   ([N_ID_PERSONA]
				   ,[C_COD_USUARIO]
				   ,[C_VAL_CLAVE]
				   ,[N_ID_TIPOUSUARIO]
				   ,[N_NUM_INTENTO]
				   ,[D_FEC_ACTIVACION]
				   ,[D_FEC_EXPIRACION]
				   ,[D_FEC_CLAVE]
				   ,[D_FEC_BLOQUEO]
				   ,[N_IND_ACTIVADO]
				   ,[N_IND_ACTIVO]
				   ,[N_ID_ESTADO]
				   ,[C_COD_USUCREACION]
				   ,[D_FEC_CREACION]
				   ,[D_FEC_CUENTA]
				   ,[C_MCA_EXTERNO])
		SELECT TMP.PERSONA_ID_GLOBAL,
			   TMP.USUARIO,
			   'l22GZw7z+Y4GkCNLyN+fCQ==',
			   0,
			   0,
			   GETDATE(),
			   GETDATE() + 30,
			   GETDATE(),
			   GETDATE() + 365,
			   1,
			   1,
			   8,
			   'admin',
			   GETDATE(),
			   GETDATE() + 365,
			   'N'
		FROM T_TEMP_USUARIOMAPFRE TMP
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
		  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
		  AND TMP.USUARIO_OBS IS NULL
			  

		INSERT INTO [dbo].[T_DET_USUARIOPERFIL]
				   ([N_ID_USUARIO]
				   ,[N_ID_PERFIL]
				   ,[N_IND_ACTIVO]
				   ,[N_ID_ESTADO]
				   ,[C_COD_USUCREACION]
				   ,[D_FEC_CREACION])
		SELECT	TMU.N_ID_USUARIO,
				TMP.COD_ROL_GLOBAL,
				1,
				8,
				'admin',
				GETDATE()
		FROM T_TEMP_USUARIOMAPFRE TMP 
		INNER JOIN T_MAE_USUARIO TMU ON TMP.USUARIO = TMU.C_COD_USUARIO AND TMP.PERSONA_ID_GLOBAL = TMU.N_ID_PERSONA
		WHERE TMP.CANAL_ID_GLOBAL IN (6, 0)
		  AND TMP.COD_ROL_GLOBAL IS NOT NULL 
		  AND TMP.USUARIO_OBS IS NULL


		PRINT 'Cargar datos de canal y punto de venta por usuario'

		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 27 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 24 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
			
		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 22 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
			
		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
			
		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 25 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
			
		insert into T_MAE_USUARIO_CANAL_PTOVENTA
		select TUP.N_ID_USUARIO, 0, 0, 0, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 26 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CANAL_PTOVENTA TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)


		PRINT 'Cargar datos de entidad y producto por usuario'

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 27 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 24 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 22 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)
			
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 0, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 26 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO)


		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 14, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 14)

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 15, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 15)

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 16, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 16)
			  
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 17, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 17)
			  
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 18, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 23 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 18)
			  
			  
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 19, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 25 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 19)
			  
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 20, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 25 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 20)
			  
		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 27, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 25 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 27)

		insert into T_MAE_USUARIO_CIA_PRODUCTO_PLAN
		select TUP.N_ID_USUARIO, 5, 28, 0, 8, 1, GETDATE(), NULL, NULL
		from T_DET_USUARIOPERFIL TUP
		where TUP.N_ID_PERFIL = 25 and not exists (
			select TB.N_ID_USUARIO
			from T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
			where TB.N_ID_USUARIO = TUP.N_ID_USUARIO
			  and TB.N_ID_PRODUCTO = 28)


		PRINT 'Actualizando USUARIO_OBS...'

		UPDATE T_TEMP_USUARIOMAPFRE
		SET USUARIO_OBS = 'Migrado',
			USUARIO_OBS_DATE = FORMAT(GETDATE(), 'yyyyMMdd')
		WHERE CANAL_ID_GLOBAL IN (6, 0)
		  AND PERSONA_ID_GLOBAL IS NOT NULL
		  AND COD_ROL_GLOBAL IS NOT NULL 
		  AND USUARIO_OBS IS NULL
  
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'Error: ' + ERROR_MESSAGE(); 
END CATCH;