USE [Mapfreqoa]
GO

DECLARE @TABLE_GRAL TABLE (
	POLIZA_ID			INT,
	N_ID_POLIZA			INT,
	N_ID_CERTIFICADO	INT,
	N_ID_SUSCRIPCION	INT,
	N_ID_COTIZACION		INT,
	N_ID_TERCERO		INT)
	select top 100 * from POLIZA_MIG_GRAL
	select top 100 * from T_MAE_POLIZA
INSERT INTO @TABLE_GRAL
SELECT 
	T1.POLIZA_ID,
	T2.N_ID_POLIZA,
	ISNULL(T3.N_ID_CERTIFICADO,0),
	ISNULL(T3.N_ID_SUSCRIPCION,0),
	ISNULL(T3.N_ID_COTIZACION,0),
	ISNULL(T4.N_ID_TERCERO,0)
FROM POLIZA_MIG_GRAL T1
JOIN T_MAE_POLIZA T2 ON T1.POLIZA_ID = T2.POLIZA_MIGRACION
LEFT JOIN T_MAE_CERTIFICADO T3 ON T2.N_ID_POLIZA = T3.N_ID_POLIZA
LEFT JOIN T_DET_ROLTERCEROCERTIFICADO T4 ON T3.N_ID_CERTIFICADO = T4.N_ID_CERTIFICADO
LEFT JOIN T_DET_ROLTERCEROCOTIZACION T5 ON T3.N_ID_COTIZACION = T5.N_ID_COTIZACION AND T4.N_ID_TERCERO = T5.N_ID_TERCERO

BEGIN TRY
BEGIN TRANSACTION

DELETE FROM T_DET_ROLTERCEROCERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_ROLTERCEROSUSCRIPCION 
WHERE N_ID_SUSCRIPCION IN (SELECT DISTINCT N_ID_SUSCRIPCION FROM @TABLE_GRAL)

DELETE RTS
FROM T_DET_ROLTERCEROSUSCRIPCION RTS INNER JOIN T_MAE_SUSCRIPCION SUS ON SUS.N_ID_SUSCRIPCION = RTS.N_ID_SUSCRIPCION
WHERE SUS.POLIZA_MIGRACION IN (SELECT DISTINCT POLIZA_ID FROM @TABLE_GRAL)

DELETE FROM T_DET_ROLTERCEROCOTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_MAE_SUSCRIPCION
WHERE N_ID_SUSCRIPCION IN (SELECT DISTINCT N_ID_SUSCRIPCION FROM @TABLE_GRAL)

DELETE FROM T_MAE_SUSCRIPCION
WHERE POLIZA_MIGRACION IN (SELECT DISTINCT POLIZA_ID FROM @TABLE_GRAL)

DELETE FROM T_DET_BITACORA_CUOTA
WHERE N_ID_CUOTA IN (SELECT DISTINCT T2.N_ID_CUOTA FROM @TABLE_GRAL T1 JOIN T_MAE_CUOTA T2 ON T1.N_ID_CERTIFICADO = T2.N_ID_CERTIFICADO)

DELETE FROM T_MAE_CUOTA
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_BITACORA_CERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_DATOPARTICULARCERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_PLANCOTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_MAE_CERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_MAE_COTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_DET_COMPONENTEPLANPOLIZA
WHERE N_ID_POLIZA IN (SELECT DISTINCT N_ID_POLIZA FROM @TABLE_GRAL)

DELETE FROM T_MAE_POLIZA
WHERE N_ID_POLIZA IN (SELECT DISTINCT N_ID_POLIZA FROM @TABLE_GRAL)

COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;

    PRINT 'Error: ' + ERROR_MESSAGE(); 

END CATCH;