USE [Mapfreqoa]
GO

DECLARE @TABLE_GRAL TABLE (
	POLIZA_ID			INT,
	N_ID_POLIZA			INT,
	N_ID_CERTIFICADO	INT,
	N_ID_SUSCRIPCION	INT,
	N_ID_COTIZACION		INT,
	N_ID_TERCERO		INT)
	select top 100 * from POLIZA_MIG_GRAL
	select top 100 * from T_MAE_POLIZA
INSERT INTO @TABLE_GRAL
SELECT 
	T1.POLIZA_ID,
	T2.N_ID_POLIZA,
	ISNULL(T3.N_ID_CERTIFICADO,0),
	ISNULL(T3.N_ID_SUSCRIPCION,0),
	ISNULL(T3.N_ID_COTIZACION,0),
	ISNULL(T4.N_ID_TERCERO,0)
FROM POLIZA_MIG_GRAL T1
JOIN T_MAE_POLIZA T2 ON T1.POLIZA_ID = T2.POLIZA_MIGRACION
LEFT JOIN T_MAE_CERTIFICADO T3 ON T2.N_ID_POLIZA = T3.N_ID_POLIZA
LEFT JOIN T_DET_ROLTERCEROCERTIFICADO T4 ON T3.N_ID_CERTIFICADO = T4.N_ID_CERTIFICADO
LEFT JOIN T_DET_ROLTERCEROCOTIZACION T5 ON T3.N_ID_COTIZACION = T5.N_ID_COTIZACION AND T4.N_ID_TERCERO = T5.N_ID_TERCERO

BEGIN TRY
BEGIN TRANSACTION

DELETE FROM T_DET_ROLTERCEROCERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_ROLTERCEROSUSCRIPCION 
WHERE N_ID_SUSCRIPCION IN (SELECT DISTINCT N_ID_SUSCRIPCION FROM @TABLE_GRAL)

DELETE RTS
FROM T_DET_ROLTERCEROSUSCRIPCION RTS INNER JOIN T_MAE_SUSCRIPCION SUS ON SUS.N_ID_SUSCRIPCION = RTS.N_ID_SUSCRIPCION
WHERE SUS.POLIZA_MIGRACION IN (SELECT DISTINCT POLIZA_ID FROM @TABLE_GRAL)

DELETE FROM T_DET_ROLTERCEROCOTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_MAE_SUSCRIPCION
WHERE N_ID_SUSCRIPCION IN (SELECT DISTINCT N_ID_SUSCRIPCION FROM @TABLE_GRAL)

DELETE FROM T_MAE_SUSCRIPCION
WHERE POLIZA_MIGRACION IN (SELECT DISTINCT POLIZA_ID FROM @TABLE_GRAL)

DELETE FROM T_DET_BITACORA_CUOTA
WHERE N_ID_CUOTA IN (SELECT DISTINCT T2.N_ID_CUOTA FROM @TABLE_GRAL T1 JOIN T_MAE_CUOTA T2 ON T1.N_ID_CERTIFICADO = T2.N_ID_CERTIFICADO)

DELETE FROM T_MAE_CUOTA
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_BITACORA_CERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_DATOPARTICULARCERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_DET_PLANCOTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_MAE_CERTIFICADO
WHERE N_ID_CERTIFICADO IN (SELECT DISTINCT N_ID_CERTIFICADO FROM @TABLE_GRAL)

DELETE FROM T_MAE_COTIZACION
WHERE N_ID_COTIZACION IN (SELECT DISTINCT N_ID_COTIZACION FROM @TABLE_GRAL)

DELETE FROM T_DET_COMPONENTEPLANPOLIZA
WHERE N_ID_POLIZA IN (SELECT DISTINCT N_ID_POLIZA FROM @TABLE_GRAL)

DELETE FROM T_MAE_POLIZA
WHERE N_ID_POLIZA IN (SELECT DISTINCT N_ID_POLIZA FROM @TABLE_GRAL)

COMMIT TRANSACTION
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;

    PRINT 'Error: ' + ERROR_MESSAGE(); 

END CATCH;






USE Mapfreqoa
GO
select * from T_MAE_USUARIO




select * from T_MAE_PERSONA where N_ID_PERSONA = 5778
select * from T_DET_PERSONA 

DECLARE @MAXID INT

DELETE FROM T_DET_PERSONA WHERE YEAR(D_FEC_CREACION) = 2024 and MONTH(D_FEC_CREACION) = 10 and day(D_FEC_CREACION) = 24
SET @MAXID = ISNULL((SELECT MAX(N_ID_DETPERSONA) FROM T_DET_PERSONA), 0)

DBCC CHECKIDENT([T_DET_PERSONA], RESEED, @MAXID)

DELETE FROM T_MAE_PERSONA WHERE YEAR(D_FEC_CREACION) = 2024 and MONTH(D_FEC_CREACION) = 10 and day(D_FEC_CREACION) = 24
SET @MAXID = ISNULL((SELECT MAX(N_ID_PERSONA) FROM T_MAE_PERSONA), 0)

DBCC CHECKIDENT([T_MAE_PERSONA], RESEED, @MAXID)

SET @MAXID = ISNULL((SELECT MAX(N_ID_USUARIO) FROM T_MAE_USUARIO), 0)

DBCC CHECKIDENT([T_MAE_USUARIO], RESEED, @MAXID)


--select *
delete from T_MAE_USUARIO
where C_COD_USUARIO = 'Migración'


delete from T_MAE_USUARIO
where C_COD_USUARIO is NULL and RTRIM(C_COD_USUCREACION) = 'Migración'

delete TMU
from T_MAE_USUARIO TMU
where C_COD_USUARIO is NULL and NOT EXISTS (select TDP.N_ID_PERSONA from T_DET_PERSONA TDP where TDP.N_ID_PERSONA = TMU.N_ID_PERSONA)

delete TDP
from T_MAE_PERSONA TMP inner join T_DET_PERSONA TDP on TMP.N_ID_PERSONA = TDP.N_ID_PERSONA
where TMP.N_ID_ENTIDAD IS NULL and RTRIM(TMP.C_COD_USUCREACION) = 'Migración' 

delete TDP
from T_MAE_PERSONA TMP inner join T_DET_PERSONA TDP on TMP.N_ID_PERSONA = TDP.N_ID_PERSONA
where TMP.N_ID_ENTIDAD IS NULL and TMP.C_OBS_DESCRIPTIVO like 'Migrac%'

delete TMP 
from T_MAE_PERSONA TMP 
where TMP.N_ID_ENTIDAD IS NULL and TMP.N_ID_PERSONA <> 1 and NOT EXISTS (select TMU.N_ID_PERSONA from T_MAE_USUARIO TMU where TMU.N_ID_PERSONA = TMP.N_ID_PERSONA)

delete TMP 
--select *
from T_MAE_PERSONA TMP 
where N_ID_TIPOIDENTIDAD is NULL 


delete TMP 
--select *
from T_MAE_PERSONA TMP 
where C_NOM_COMPLETO like 'Migración%'


select distinct USUARIO_OBS from T_TEMP_USUARIOMAPFRE
select * from T_TEMP_USUARIOMAPFRE where USUARIO_OBS = 'Duplicado' order by 2

select * from T_MAE_USUARIO_CIA_PRODUCTO_PLAN
select * from T_MAE_USUARIO_CANAL_PTOVENTA
select * from T_DET_USUARIOPERFIL








USE Mapfreqoa

--REEMPLAZAR VALOR POR LA FECHA (YYYYMMDD) QUE SE DESEA HACER ROLLBACK 
DECLARE @EXEC_DATE CHAR(8) = '20241024' 

DECLARE @MIG TABLE (PERSONA_ID INT, USUARIO_ID INT)

DECLARE @MAXID INT = 0



INSERT INTO @MIG
SELECT TPER.N_ID_PERSONA, TUSE.N_ID_USUARIO
FROM T_TEMP_USUARIOMAPFRE TEMP 
INNER JOIN T_MAE_PERSONA TPER ON TPER.C_VAL_CODREFERENCIA = RTRIM(LTRIM(STR(TEMP.USUARIO_ID))) AND TEMP.USUARIO_OBS_DATE = @EXEC_DATE
INNER JOIN T_MAE_USUARIO TUSE ON TUSE.C_COD_USUARIO = TEMP.USUARIO AND TPER.N_ID_PERSONA = TUSE.N_ID_PERSONA
WHERE TEMP.USUARIO_OBS = 'Migrado'
  AND TEMP.CANAL_ID_GLOBAL IS NOT NULL

--GO


DELETE TB
FROM T_MAE_USUARIO_CIA_PRODUCTO_PLAN TB
INNER JOIN @MIG MIG ON TB.N_ID_USUARIO = MIG.USUARIO_ID AND TB.N_ID_COMPANIA = 5 AND TB.N_ID_ESTADO = 8

DELETE TB
FROM T_MAE_USUARIO_CANAL_PTOVENTA TB
INNER JOIN @MIG MIG ON TB.N_ID_USUARIO = MIG.USUARIO_ID AND TB.N_ID_ESTADO = 8


DELETE TB
FROM T_DET_USUARIOPERFIL TB
INNER JOIN @MIG MIG ON TB.N_ID_USUARIO = MIG.USUARIO_ID AND TB.N_ID_ESTADO = 8

SET @MAXID = ISNULL((SELECT MAX(N_ID_DETUSUARIOPERFIL) FROM T_DET_USUARIOPERFIL), 0)

DBCC CHECKIDENT([T_DET_USUARIOPERFIL], RESEED, @MAXID)



DELETE TB
FROM T_MAE_USUARIO TB
INNER JOIN @MIG MIG ON TB.N_ID_USUARIO = MIG.USUARIO_ID AND TB.N_ID_PERSONA = MIG.PERSONA_ID AND TB.N_ID_ESTADO = 8

SET @MAXID = ISNULL((SELECT MAX(N_ID_USUARIO) FROM T_MAE_USUARIO), 0)

DBCC CHECKIDENT([T_MAE_USUARIO], RESEED, @MAXID)


DELETE TB
FROM T_DET_PERSONA TB
INNER JOIN @MIG MIG ON TB.N_ID_PERSONA = MIG.PERSONA_ID AND TB.N_ID_ESTADO = 8

SET @MAXID = ISNULL((SELECT MAX(N_ID_DETPERSONA) FROM T_DET_PERSONA), 0)

DBCC CHECKIDENT([T_DET_PERSONA], RESEED, @MAXID)



DELETE TB
FROM T_MAE_PERSONA TB
INNER JOIN @MIG MIG ON TB.N_ID_PERSONA = MIG.PERSONA_ID AND TB.N_ID_ESTADO = 8

SET @MAXID = ISNULL((SELECT MAX(N_ID_PERSONA) FROM T_MAE_PERSONA), 0)

DBCC CHECKIDENT([T_MAE_PERSONA], RESEED, @MAXID)


--GO


UPDATE T_TEMP_USUARIOMAPFRE
SET USUARIO_OBS = NULL,
	USUARIO_OBS_DATE = NULL
WHERE CANAL_ID_GLOBAL IN (6, 0)
  AND COD_ROL_GLOBAL IS NOT NULL 
  AND USUARIO_OBS = 'Migrado'
  AND USUARIO_OBS_DATE = @EXEC_DATE
  
GO
